name: orderbot
channels:
  - defaults
dependencies:
  - anyio=4.10.0
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=4.1.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - executing=2.2.1
  - expat=2.7.3
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - idna=3.11
  - ipykernel=6.31.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mistune=3.1.2
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openssl=3.0.18
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=4.0.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.28.0
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.51.1
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.5.1
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.6.3
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - bokeh==3.8.2
      - contourpy==1.3.3
      - distro==1.9.0
      - jiter==0.12.0
      - linkify-it-py==2.0.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - narwhals==2.15.0
      - numpy==2.4.1
      - openai==2.15.0
      - pandas==2.3.3
      - panel==1.8.5
      - param==2.3.1
      - pillow==12.1.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyviz-comms==3.0.6
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uc-micro-py==1.0.3
      - xyzservices==2025.11.0
prefix: /Users/yinyueyang/opt/anaconda3/envs/orderbot
